<a href="https://colab.research.google.com/github/rzangef21/spb-kelompok-2/blob/main/UTS_SBP_Kelompok2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Dataset_sales.csv')
df.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Total_Revenue,Store_Location,Payment_Method
0,T0001,2024-10-06,Pepsodent Toothpaste,Personal Care,NaN,15000,675000.0,Jakarta,Cash
1,T0002,2024-10-01,ABC Kecap Manis 620ml,Groceries,60.0,18000,1080000.0,Jakarta,Card
2,T0003,2024-10-01,Lifebuoy Body Wash,Personal Care,17.0,25000,425000.0,Medan,Cash
3,T0004,2024-10-06,Milo 1kg,Drinks,95.0,90000,8550000.0,Bandung,Cash
4,T0005,2024-10-03,Indomie Goreng,Instant Noodles,30.0,3000,90000.0,Surabaya,Card

In [ ]:
df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors='coerce')

In [ ]:
df['Units_Sold'] = df['Units_Sold'].fillna(df['Units_Sold'].median())
df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].median())

In [ ]:
df.loc[df['Total_Revenue'].isna(), 'Total_Revenue'] = \
    df['Units_Sold'] * df['Unit_Price']

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  4000 non-null   object
 1   Date            4000 non-null   datetime64[ns]
 2   Product_Name    4000 non-null   object
 3   Category        4000 non-null   object
 4   Units_Sold      4000 non-null   float64
 5   Unit_Price      4000 non-null   float64
 6   Total_Revenue   4000 non-null   float64
 7   Store_Location  4000 non-null   object
 8   Payment_Method  4000 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 281.4+ KB

In [ ]:
df['Transaction_ID'].duplicated().sum()

np.int64(0)

In [ ]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [ ]:
df['Sales_Level'] = pd.qcut(df['Total_Revenue'], q=3, labels=['Low','Medium','High'])

In [ ]:
monthly = df.groupby(pd.Grouper(key='Date', freq='ME'))['Total_Revenue'].sum().reset_index()

In [ ]:
monthly['Growth'] = monthly['Total_Revenue'].pct_change()

monthly['Status'] = monthly['Growth'].apply(
    lambda x: 'Naik' if x > 0 else ('Turun' if x < 0 else 'Stagnan')
)

In [ ]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  4000 non-null   object
 1   Date            4000 non-null   datetime64[ns]
 2   Product_Name    4000 non-null   object
 3   Category        4000 non-null   object
 4   Units_Sold      4000 non-null   float64
 5   Unit_Price      4000 non-null   float64
 6   Total_Revenue   4000 non-null   float64
 7   Store_Location  4000 non-null   object
 8   Payment_Method  4000 non-null   object
 9   Year            4000 non-null   int32
 10  Month           4000 non-null   int32
 11  Day             4000 non-null   int32
 12  Sales_Level     4000 non-null   category
dtypes: category(1), datetime64[ns](1), float64(3), int32(3), object(5)
memory usage: 332.3+ KB

,Date,Units_Sold,Unit_Price,Total_Revenue,Year,Month,Day
count,4000,4000.000000,4000.000000,4.000000e+03,4000.0,4000.0,4000.000000
mean,2024-10-03 13:17:45.600000256,54.776750,21205.200000,1.168871e+06,2024.0,10.0,3.554000
min,2024-10-01 00:00:00,10.000000,2800.000000,3.000000e+04,2024.0,10.0,1.000000
25%,2024-10-02 00:00:00,33.000000,7500.000000,2.900000e+05,2024.0,10.0,2.000000
50%,2024-10-04 00:00:00,55.000000,15000.000000,6.600000e+05,2024.0,10.0,4.000000
75%,2024-10-05 00:00:00,76.000000,25000.000000,1.395000e+06,2024.0,10.0,5.000000
max,2024-10-06 00:00:00,100.000000,90000.000000,9.000000e+06,2024.0,10.0,6.000000
std,NaN,25.623115,21484.926774,1.435257e+06,0.0,0.0,1.704204